### ISSUE TITLE
lines 51064-51070

### ISSUE THREAD

**Issue by adamlek** [unimorph/eng#2]
Looking at the data, between lines: 51064 and 51070 there is an entry for "ind." with punctuation. This seems like an incorrect entry as "ind." would be a shortened word and not the full lemma (and it's somewhat strange to inflect a shortened word, the full form is more appropriate).
However, it's unclear what lemma this actually refers to.

ind.	ind'd	V;PST
ind.	ind'd	V;V.PTCP;PST
ind.	inded	V;PST
ind.	inded	V;V.PTCP;PST
ind.	inding	V;V.PTCP;PRS
ind.	ind's	V;3;SG;PRS
ind.	inds	V;3;SG;PRS
ind.	ind.	V;NFIN

**Comment by kbatsuren** [comment]
The new update doesn't have this entry because simply Wiktionary has no verb form for `ind.` at this moment.
[https://en.wiktionary.org/wiki/ind.](https://en.wiktionary.org/wiki/ind.) 

I suppose I can close this issue. :)
