### ISSUE TITLE
verb only

### ISSUE THREAD

**Issue by arademaker** [unimorph/eng#4]
Why we don't have nouns or adjectives and only verbs?

**Comment by kbatsuren** [comment]
We will be adding the full English file very soon. I believe just in a few days. If you need the data immediately, drop me an email. khuyagbaatar.b@gmail.com

**Comment by kbatsuren** [comment]
Hi @arademaker,

The current update contains all categories including nouns, adjectives, and verbs. So let's close this issue. 

Best regards.
